name: Windows Build - Latest Version

on:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        uses: krdlab/setup-haxe@38fd78cc3a7960b281cf4a33a63a9c1543ac4598
        with:
          haxe-version: 4.2.5

      - name: Restore Cache
        uses: actions/cache@main
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows

      - name: Install Haxelib
        run: |
          haxelib install lime 8.0.1 --always --quiet
          haxelib install hxcpp --always --quiet
          haxe --main Setup -D analyzer-optimize --interp
          haxelib set hxCodec 2.5.1 --always
          haxelib set lime 8.0.1 --always
          haxelib set openfl 9.2.1 --always
          haxelib set hxcpp 4.2.1 --always
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin

      - name: Uploading new cache
        uses: actions/cache@main
        with:
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
